/* QUAL A MODA DOS SALARIOS ? */

/* QUAL A MODA DEPARTAMENTAL, QUAL O DEPARTAMENTO QUE MAIS EMPREGA */

/* QUAL O DESVIO PADRAO DE CADA DEPARTAMENTO */

/* CALCULE A MEDIANA SALARIAL DE TODO O SET DE DADOS */

/* QUAL A AMPLITUDE DE TODOS OS SALARIOS? */

/* CALCULE AS PRINCIPAIS MEDIDAS ESTATISTICAS POR DEPARTAMENTO */

/* QUAL O DEPARTAMENTO TE DA UM MAIOR PROBLABILIDADE DE GANHAR MAIS ? */