/* MOSTRAR O PADRAO DE DATA */

SHOW DATESTYLE

/* PARA ALTERAR O PADRÃO DE DATA BASTA IR NO DIRETORIO DO POSTGRESQL ->
    DATA -> postgresql.config -> datestyle e alterar para 
    d - day
    m - month
    y - year
para o ordem que deseja  */
                                                          
/* FUNÇÕES DE AGREGAÇÕES */

/* QUERY SIMPLES */      

SELECT * FROM FUNCIONARIOS;

/* CONTANDO O NUMERO DE OCORRENCIAS */

SELECT COUNT(*) FROM FUNCIONARIOS;
SELECT COUNT(*) FROM DEPARTAMENTOS;
SELECT COUNT(*) FROM LOCALIZACOES;

/* AGRUPANDO POR SEXO COM GROUP BY */

SELECT COUNT(*) FROM FUNCIONARIOS
GROUP BY SEXO;

/* COLOCANDO O NOME DA COLUNA */

SELECT SEXO, COUNT(*) AS QUANTIDADE FROM FUNCIONARIOS
GROUP BY SEXO;

/* MOSTRANDO O NUMERO DE FUNCIONARIOS EM CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, COUNT(*) FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* EXIBINDO O MAXIMO DE SALARIOS - 149929 */

SELECT MAX(SALARIO) AS "SALARIO MAXIMO" FROM FUNCIONARIOS;

/* EXIBINDO O MINIMO DE SALARIOS - 40138*/

SELECT MIN(SALARIO) AS "SALARIO MINIMO" FROM FUNCIONARIOS;

/* EXIBINDO MAXIMO E MINIMO JUNTOS */

SELECT MIN(SALARIO) AS "SALARIO MINIMO", MAX(SALARIO) AS "SALARIO MAXIMO"
FROM FUNCIONARIOS;

/* EXIBINDO O MAXIMO E O MINIMO DE CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, MIN(SALARIO) AS "SALARIO MINIMO", MAX(SALARIO) AS "SALARIO MAXIMO"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* EXIBINDO O MAXIMO E O MINIMO POR SEXO */

SELECT SEXO, MIN(SALARIO) AS "SALARIO MINIMO", MAX(SALARIO) AS "SALARIO MAXIMO"
FROM FUNCIONARIOS
GROUP BY SEXO;

/* ESTATISTICAS */

/* MOSTRANDO UMA QUANTIDADE LIMITADA DE LINHAS */

SELECT * FROM FUNCIONARIOS
LIMIT 10;

/* QUAL O GASTO TOTAL DE SALARIO PAGO PELA EMPRESA */

SELECT SUM(SALARIO) AS TOTAL FROM FUNCIONARIOS;

/* QUAL O MONTANTE TOTAL QUE CADA DEPARTAMENTO RECEBE DE SALARIO */

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* POR DEPARTAMENTO QUAL O TOTAL E A MEDIA PAGA PARA OS FUNCIONARIOS */

SELECT SUM(SALARIO) AS TOTAL, AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS;

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL, AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* ORDENANDO */

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL, AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3;

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL, AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3 ASC;

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL, AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3 DESC;

/*

SOMA = TOTAL
MAX = MAIOR NUMERO
MIN = MENOR NUMERO 
MEDIA = A MEDIA DE UM AGRUPADO DE NUMEROS
MEDIANA = O MEIO DE UM GRUPO DE NUMEROS
MODA = QUANTAS VEZES SE REPETEM UM NUMERO
AMPLITUDE = O MAIOR MENOS O MENOR
VARIANCA = MÉDIA, SUBTRAE CADA MEMBRO DA MÉDIA, ELEVAR AO QUADRADO,
           SOMAR TODOS OS RESULTADOS, DIVIDIR OS RESULTADOS PELO N° DE OCORRENCIAS
           TIRAR A RAIZ DA VARIANCIA, DIVIDIR DP PELA MÉDIA
COEF.VAR = QUANDO ESTÁ MANIPULANDO DADOS DIFERENTE, DESVIP DIVIDO PELA MEDIA MULTIPLICADO POR 100

*/ 

/* INSERINDO DADOS DE UMA PLANILHA NUMA TABELA */

CREATE TABLE MAQUINAS(
    MAQUINA VARCHAR(30),
    DIA INT,
    QTD NUMERIC(10,2)
);

COPY MAQUINAS
FROM 'C:\Users\Public\Downloads\LogMaquinas.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM MAQUINAS

/* QUAL A MEDIA DE CADA MAQUINA */

SELECT MAQUINA, AVG(QTD) AS MEDIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

/* ARREDONDANDO */

SELECT MAQUINA, ROUND(AVG(QTD),2) AS MEDIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

/* QUAL A MODA DAS QUANTIDADES */

SELECT MAQUINA, QTD, COUNT(*) AS MODA
FROM MAQUINAS
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC

/* QUAL A  MODA DAS QUANTIDADES DE CADA MAQUINA */

SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

/* MODA DO DATASET INTEIRO */
