/* MOSTRAR O PADRAO DE DATA */

SHOW DATESTYLE

/* PARA ALTERAR O PADRÃO DE DATA BASTA IR NO DIRETORIO DO POSTGRESQL ->
    DATA -> postgresql.config -> datestyle e alterar para 
    d - day
    m - month
    y - year
para o ordem que deseja  */
                                                          
/* FUNÇÕES DE AGREGAÇÕES */


/* QUERY SIMPLES */      

SELECT * FROM FUNCIONARIOS;

/* CONTANDO O NUMERO DE OCORRENCIAS */

SELECT COUNT(*) FROM FUNCIONARIOS;
SELECT COUNT(*) FROM DEPARTAMENTOS;
SELECT COUNT(*) FROM LOCALIZACOES;

/* AGRUPANDO POR SEXO COM GROUP BY */

SELECT COUNT(*) FROM FUNCIONARIOS
GROUP BY SEXO;

/* COLOCANDO O NOME DA COLUNA */

SELECT SEXO, COUNT(*) AS QUANTIDADE FROM FUNCIONARIOS
GROUP BY SEXO;

/* MOSTRANDO O NUMERO DE FUNCIONARIOS EM CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, COUNT(*) FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* EXIBINDO O MAXIMO DE SALARIOS - 149929 */

SELECT MAX(SALARIO) AS "SALARIO MAXIMO" FROM FUNCIONARIOS;

/* EXIBINDO O MINIMO DE SALARIOS - 40138*/

SELECT MIN(SALARIO) AS "SALARIO MINIMO" FROM FUNCIONARIOS;

/* EXIBINDO MAXIMO E MINIMO JUNTOS */

SELECT MIN(SALARIO) AS "SALARIO MINIMO", MAX(SALARIO) AS "SALARIO MAXIMO"
FROM FUNCIONARIOS;

/* EXIBINDO O MAXIMO E O MINIMO DE CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, MIN(SALARIO) AS "SALARIO MINIMO", MAX(SALARIO) AS "SALARIO MAXIMO"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* EXIBINDO O MAXIMO E O MINIMO POR SEXO */

SELECT SEXO, MIN(SALARIO) AS "SALARIO MINIMO", MAX(SALARIO) AS "SALARIO MAXIMO"
FROM FUNCIONARIOS
GROUP BY SEXO;

/* ESTATISTICAS */

/* MOSTRANDO UMA QUANTIDADE LIMITADA DE LINHAS */

SELECT * FROM FUNCIONARIOS
LIMIT 10;

/* QUAL O GASTO TOTAL DE SALARIO PAGO PELA EMPRESA */

SELECT SUM(SALARIO) AS TOTAL FROM FUNCIONARIOS;

/* QUAL O MONTANTE TOTAL QUE CADA DEPARTAMENTO RECEBE DE SALARIO */

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* POR DEPARTAMENTO QUAL O TOTAL E A MEDIA PAGA PARA OS FUNCIONARIOS */

SELECT SUM(SALARIO) AS TOTAL, AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS;

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL, AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* ORDENANDO */

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL, AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3;

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL, AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3 ASC;

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL, AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3 DESC;

/*

SOMA = TOTAL
MAX = MAIOR NUMERO
MIN = MENOR NUMERO 
MEDIA = A MEDIA DE UM AGRUPADO DE NUMEROS
MEDIANA = O MEIO DE UM GRUPO DE NUMEROS
MODA = QUANTAS VEZES SE REPETEM UM NUMERO
AMPLITUDE = O MAIOR MENOS O MENOR
VARIANCA = MÉDIA, SUBTRAE CADA MEMBRO DA MÉDIA, ELEVAR AO QUADRADO,
           SOMAR TODOS OS RESULTADOS, DIVIDIR OS RESULTADOS PELO N° DE OCORRENCIAS
           TIRAR A RAIZ DA VARIANCIA, DIVIDIR DP PELA MÉDIA
COEF.VAR = QUANDO ESTÁ MANIPULANDO DADOS DIFERENTE, DESVIP DIVIDO PELA MEDIA MULTIPLICADO POR 100

*/ 

/* Banco de Dados -> 1,2 e 3 Formas normais
Evitam reduncancia, consequentemente poupam espaço em disco.
Consomem muito processamento em função de Joins. Queries lentas

Data Science e B.I -> Focam em agregaçoes e performance. Não se 
preocupam com espaço em disco. Em B.I, modelagem mínima (DW)
em Data Science, preferencialmente modelagem Colunar */

/* O servidor de maquinas gerou um arquivo de log CSV.
Vamos importá-lo e analisa-lo dentro do nosso banco */

/* INSERINDO DADOS DE UMA PLANILHA NUMA TABELA */

CREATE TABLE MAQUINAS(
    MAQUINA VARCHAR(30),
    DIA INT,
    QTD NUMERIC(10,2)
);

COPY MAQUINAS
FROM 'C:\Users\Public\Downloads\LogMaquinas.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM MAQUINAS

/* QUAL A MEDIA DE CADA MAQUINA */

SELECT MAQUINA, AVG(QTD) AS MEDIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

/* ARREDONDANDO */

SELECT MAQUINA, ROUND(AVG(QTD),2) AS MEDIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

/* QUAL A MODA DAS QUANTIDADES */

SELECT MAQUINA, QTD, COUNT(*) AS MODA
FROM MAQUINAS
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC

/* QUAL A  MODA DAS QUANTIDADES DE CADA MAQUINA */

SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

/* MODA DO DATASET INTEIRO */

SELECT QTD, COUNT(*)
FROM MAQUINAS
GROUP BY QTD
ORDER BY 2 DESC;

/* QUAL O MAXIMO E MINIMO E AMPLITUDE DE CADA MAQUINA */

SELECT MAQUINA,
    MAX(QTD) AS MAXIMO,
    MIN(QTD) AS MINIMO,
    MAX(QTD) - MIN(QTD) AS AMPLITUDE
    FROM MAQUINAS
    GROUP BY MAQUINA
    ORDER BY 4 DESC;

/* ACRESCENTE A MEDIA DO RELATORIO */    

SELECT MAQUINA,
    ROUND(AVG(QTD),2) AS MEDIA,
    MAX(QTD) AS MAXIMO,
    MIN(QTD) AS MINIMO,
    MAX(QTD) - MIN(QTD) AS AMPLITUDE
    FROM MAQUINAS
    GROUP BY MAQUINA
    ORDER BY 4 DESC;

/* DESVIO PADRAO E VARIANCIA */

STDDEV_POP(COLUNA)
VAR_POP(COLUNA)

SELECT MAQUINA,
    ROUND(AVG(QTD),2) AS MEDIA,
    MAX(QTD) AS MAXIMO,
    MIN(QTD) AS MINIMO,
    MAX(QTD) - MIN(QTD) AS AMPLITUDE,
    ROUND(STDDEV_POP(QTD), 2) AS DESV_PAD,
    ROUND(VAR_POP(QTD), 2) AS VARIANCIA
    FROM MAQUINAS
    GROUP BY MAQUINA
    ORDER BY 4 DESC;

/* CALCULO DE VARIANCIA */

CREATE OR REPLACE FUNCTION _final_median(numeric[])
   RETURNS numeric AS
$$
   SELECT AVG(val)
   FROM (
     SELECT val
     FROM unnest($1) val
     ORDER BY 1
     LIMIT  2 - MOD(array_upper($1, 1), 2)
     OFFSET CEIL(array_upper($1, 1) / 2.0) - 1
   ) sub;
$$
LANGUAGE 'sql' IMMUTABLE;

CREATE AGGREGATE median(numeric) (
  SFUNC=array_append,
  STYPE=numeric[],
  FINALFUNC=_final_median,
  INITCOND='{}'
);

SELECT ROUND(MEDIAN(QTD), 2) AS MEDIANA
FROM MAQUINAS;

SELECT ROUND(MEDIAN(QTD), 2) AS MEDIANA
FROM MAQUINAS 
WHERE MAQUINA = 'Maquina 01';

SELECT ROUND(MEDIAN(QTD), 2) AS MEDIANA
FROM MAQUINAS 
WHERE MAQUINA = 'Maquina 02';

SELECT ROUND(MEDIAN(QTD), 2) AS MEDIANA
FROM MAQUINAS 
WHERE MAQUINA = 'Maquina 03';

INSERT INTO MAQUINAS VALUES('Maquina 01', 11, 15.9);
INSERT INTO MAQUINAS VALUES('Maquina 02', 11, 15.4);
INSERT INTO MAQUINAS VALUES('Maquina 03', 11, 15.7);
INSERT INTO MAQUINAS VALUES('Maquina 01', 12, 12.38);
INSERT INTO MAQUINAS VALUES('Maquina 02', 12, 12.24);
INSERT INTO MAQUINAS VALUES('Maquina 03', 12, 12.45);

DELETE FROM MAQUINAS WHERE DIA = 11 OR DIA = 12

