/* CURSORES */

CREATE DATABASE CURSORES;

USE CURSORES;

CREATE TABLE VENDEDORES(
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT
);

INSERT INTO VENDEDORES VALUES(NULL, 'MAFRA', 45521,321351,35136);
INSERT INTO VENDEDORES VALUES(NULL, 'CLARA', 7537,75350,7527570);
INSERT INTO VENDEDORES VALUES(NULL, 'JOAO', 452450,20427);
INSERT INTO VENDEDORES VALUES(NULL, 'LILLIAN', 65956,54615,47537);
INSERT INTO VENDEDORES VALUES(NULL, 'ANTONIO', 271853,41234,41275);
INSERT INTO VENDEDORES VALUES(NULL, 'GLORIA', 78642,73836,5237);

SELECT NOME, (JAN+FEV+MAR) AS TOTAL FROM VENDEDORES;
SELECT NOME, (JAN+FEV+MAR) AS TOTAL, (JAN+FEV+MAR)/3 AS MEDIA FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
    NOME VARCHAR(30),
    JAN INT,
    FEV INT,
    MAR INT,
    TOTAL INT,
    MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN
    DECLARE FIM INT DEFAULT 0;
    DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
    DECLARE VNOME VARCHAR(50);

    DECLARE REG CURSOR FOR(
        SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
    );

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
    
    OPEN REG;

    REPEAT 

        FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
        IF NOT FIM THEN 
            
            SET VTOTAL = VAR1 + VAR2 + VAR3;
            SET VMEDIA = VTOTAL / 3;
            
            INSERT INTO VEND_TOTAL VALUES(VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
        END IF;

    UNTIL FIM END REPEAT;

    CLOSE REG;
END
$

DELIMITER ;

SELECT * FROM VEND_TOTAL;

CALL INSEREDADOS();