/* Modelagem Básica -
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS*/ 

CLIENTE

NOME - CARACTER(30) 
CPF - NUMERICO(11)
EMAIL - CARACTER(30) 
TELEFONE - CARACTER(30) 
ENDERECO - CARACTER(100) 
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO BANCO DE DADOS */

CREATE DATABASE EXEMPLO

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),.
    EMAIL VARCHAR(30),
    CPF INT(11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTES;

/* SINTAXE BASICA DE INSERÇÃO - INSERT INTO {TABELA}*/

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES ('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '2293110', 'MATA-LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('JORGE', 'M', NULL, 885755896, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE (NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES ('LILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES ('ANA', 'F', 'ANA@GLOBO.COM', 85548962, '5485569858', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                           ('CARLA', 'F', 'CARLA@TERATI.COM.BR', 7745828, '66574758', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

/* O COMANDO SELECT (PROJEÇÃO) */

SELECT NOW() AS DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO 
    1° - SELECT // Coluna a ser projetada;
    2° - FROM // Tabela a ser filtrada; 
    3° - WHERE // Condição 
*/

SELECT NOME, SEXO 
FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO 
FROM CLIENTE
WHERE SEXO = 'F';
 
SELECT NOME, SEXO 
FROM CLIENTE
WHERE ENDERECO 
LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA */

SELECT NOME, SEXO 
FROM CLIENTE
WHERE ENDERECO 
LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE ENDERECO 
LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE ENDERECO 
LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE ENDERECO 
LIKE '%CENTRO%';


/* Exercicio Livraria */

/* Criação da Tabela e inserção de dados */
CREATE DATABASE LIVRARIA;
CREATE TABLE(
    NOME_LIVRO VARCHAR(100),
    NOME_AUTOR VARCHAR(30),
    SEXO_AUTOR CHAR(1),
    LIVRO_PAGS INT(4),
    NOME_EDITORA VARCHAR(30),
    VALOR_LIVRO DECIMAL(5,2),
    ESTADO_EDITORA CHAR(2),
    ANO_LIVRO INT(4)
)

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, LIVRO_PAGS, NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_LIVRO) 
VALUES 
('Cavaleiro Real', 'Ana Claudia', 'F', 465, 'Atlas', 49,90, 'RJ', 2009),
('SQL para leigos', 'João Nunes', 'M', 450, 'Addilson', 98.00, 'SP', 2018),
('Receitas Caseiras', 'Celia Tavares', 'F', 210, 'Atlas', 45.00, 'RJ', 2008),
('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', 2018),
('Habitos Saudáveis', 'Eduardo Santos', 'M', 390, 'Beta', 150.98, 'RJ', 2019),
('A Casa Marrom', 'Hermes Macedo', 'M', 250, 'Bubba', 60.00, 'MG', 2016),
('Estacio Querido', 'Geraldo Francisco', 'M', 310, 'Insignia', 100.00, 'ES', 2015),
('Pra sempre amigas', 'Leda Silva', 'F', 510, 'Insignia', 78.98, 'ES', 2011),
('Copas Inesqueciveis', 'Marco Alcantara', 'M', 200, 'Larson', 130.98, 'RS', 2018),
('O poder da mente', 'Clara Mafra', 'F', 120, 'Continental', 56.58, 'SP', 2017);

/* Questoes de 1 - 6 */
SELECT * FROM livraria.livros;

SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;

SELECT NOME_LIVRO, ESTADO_EDITORA FROM LIVROS WHERE SEXO_AUTOR = 'M';

SELECT NOME_LIVRO, LIVRO_PAGS FROM LIVROS WHERE SEXO_AUTOR = 'F';

SELECT VALOR_LIVRO FROM LIVROS WHERE ESTADO_EDITORA = 'SP';

SELECT NOME_AUTOR, SEXO_AUTOR FROM LIVROS WHERE SEXO_AUTOR = 'M' AND ESTADO_EDITORA = 'SP' OR SEXO_AUTOR = 'M' AND ESTADO_EDITORA = 'RJ'