/* TSQL É UM BLOCO DE LINGUAGEM DE PROGRAMACAO.
PROGRAMAS SAO UNIDADES QUE PODEM SER CHAMADAS DE BLOCOS ANONIMOS.
BLOCOS ANONIMOS NAO RECEBEM NOME, POIS NAO SAO SALVOS NO BANCO.
CRIAMOS BLOCOS ANONIMOS QUANDO IREMOS EXECUTA-LOS UMA SO VEZ OU TESTAR ALGO. */

/* BLOCO DE EXECUCAO */

BEGIN 
    PRINT 'PRIMEIRO BLOCO'
END 
GO

/* BLOCOS DE ATRIBUICAO DE VARIAVEIS */

DECLARE
    @CONTADOR INT
BEGIN 
    SET @CONTADOR = 5
    PRINT @CONTADOR
END
GO

SELECT @CONTADOR -- ERRO POR QUE ESTA FORA DO BLOCO

/* NO SQL SERVER CADA COLUNA VARIAVEL LOCAL EXPRESSAO E PARAMETRO TEM UM TIPO. */

DECLARE 
    @V_NUMERO NUMERIC(10, 2) = 100.52,
    @V_DATA DATETIME = '20170207'
BEGIN
    PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
    PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR, @V_NUMERO)
    PRINT 'VALOR DE DATA: ' + CAST(@V_DATA AS VARCHAR)
    PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 121)
    PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 120)
    PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 105)
END
GO

CREATE TABLE CARROS(
    CARRO VARCHAR(20),
    FABRICANTE VARCHAR(30)
)
GO

INSERT INTO CARROS VALUES('KA','FORD')
INSERT INTO CARROS VALUES('FIESTA','FORD')
INSERT INTO CARROS VALUES('PRISMA','FORD')
INSERT INTO CARROS VALUES('CLIO','RENAULT')
INSERT INTO CARROS VALUES('SANDERO','RENAULT')
INSERT INTO CARROS VALUES('CHEVETE','CHEVROLET')
INSERT INTO CARROS VALUES('OMEGA','CHEVROLET')
INSERT INTO CARROS VALUES('PALIO','FIAT')
INSERT INTO CARROS VALUES('DOBLO','FIAT')
INSERT INTO CARROS VALUES('UNO','FIAT')
INSERT INTO CARROS VALUES('GOL','VOLKSWAGEM')
GO

DECLARE 
    @V_CONTADOR_FORD INT,
    @V_CONTADOR_FIAT INT

BEGIN
    -- METODO 1 - O SELECT PRECISA RETORNAR UMA SIMPLES COLUNA E UM SO RESULTADO
    SET @V_CONTADOR_FORD = (SELECT COUNT(*) FROM CARROS
    WHERE FABRICANTE = 'FORD')

    PRINT 'QUANTIDADE FORD: ' + CAST(@V_CONTADOR_FORD AS VARCHAR)

    -- METODO 2
    SELECT @V_CONTADOR_FIAT = COUNT(*) FROM CARROS WHERE FABRICANTE = 'FIAT'

    PRINT 'QUANTIDADE FIAT: ' + CONVERT(VARCHAR, @V_CONTADOR_FIAT)
END
GO

/* BLOCOS IF E ELSE 
BLOCO NOMEADO - PROCEDURES
*/

DECLARE 
    @NUMERO INT = 5
BEGIN
    IF @NUMERO = 5 -- EXPRESSAO BOOLEANA - TRUE
        PRINT 'O VALOR É VERDADEIRO'
    ELSE 
        PRINT 'O VALOR É FALSO' 
END 
GO 

/* CASE */

DECLARE
    @CONTADOR INT
BEGIN
    SELECT -- O CASE REPRESENTA UMA COLUNA  
    CASE
        WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
        WHEN FABRICANTE = 'CHEVROLET' THEN 'FAIXA 2'
        ELSE 'OUTRAS FAIXAS'
    END AS "INFORMACOES",
    *
    FROM CARROS
END
GO

CREATE PROC VERIFICADOR @NUM INT
AS
BEGIN
    IF @NUM = 5
        PRINT 'NUMERO VERDADEIRO'
    ELSE 
        PRINT 'NUMERO FALSO'
END
GO

/* LOOPS WHILE */

DECLARE 
    @I INT = 1 
BEGIN
    WHILE (@I < 15)
    BEGIN
        PRINT 'VALOR DE I: ' + CAST(@I AS VARCHAR)
        SET @I = @I + 1
    END
END
GO

