CREATE DATABASE PROJETO_OFICINA;

USE PROJETO_OFICINA;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME CHAR(30) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    ID_CARRO INT UNIQUE
); 

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CEL', 'RES', 'COM') NOT NULL,
    NUMERO VARCHAR(30) NOT NULL,
    ID_CLIENTE INT
);

CREATE TABLE MARCA(
  IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
  MARCA VARCHAR(30) UNIQUE NOT NULL  
);

CREATE TABLE CARRO(
    IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(30) UNIQUE NOT NULL,
    PLACA VARCHAR(30) UNIQUE NOT NULL,
    ID_MARCA INT
);

CREATE TABLE COR(
    IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    COR VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_COR(
    ID_CARRO INT,
    ID_COR INT,
    PRIMARY KEY(ID_CARRO, ID_COR)
);

/* CONSTRAINTS */

ALTER TABLE TELFEONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

/* PREENCHER */

INSERT INTO CLIENTE VALUES(
    NULL,
    "ANDRE",
    "M",
    1
);

INSERT INTO CARRO VALUES(
    NULL,
    "SUPRA",
    "SUP-1234",
    1
);

INSERT INTO MARCA VALUES(
    NULL,
    "TOYOTA"
);

INSERT INTO COR VALUES(
    NULL,
    "PRATA"
);

INSERT INTO TELEFONE VALUES(
    NULL,
    "CEL",
    "1234-5687",
    1
);

INSERT INTO CARRO_COR VALUES(
    1,
    1
);
