/* SELECAO PROJECAO E JUNCAO */

/* PROJECAO -> É TUDO QUE VOCE QUER VER NA TELA */
SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2  AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW()
FROM CLIENTE;

/* SELECAO -> É U SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA
A CLAUSULA DE SELECAO É O WHERE */
SELECT NOME, SEXO, EMAIL -- PROJECAO
FROM CLIENTE -- ORIGEM
WHERE SEXO = 'F'; -- SELECAO

SELECT NUMERO, TIPO -- PROJECAO
FROM TELEFONE -- ORIGEM
WHERE TIPO = 'CEL'; -- SELECAO

/* JUNCAO -> JOIN*/
SELECT NOME, EMAIL, ID_CLIENTE
FROM CLIENTE;

SELECT IDCLIENTE, BAIRRO, CIDADE
FROM ENDERECO;

/* NOME, SEXO, BAIRRO, CIDADE */
SELECT NOME, SEXO, BAIRRO, CIDADE -- PROJECAO
FROM CLIENTE, ENDERECO -- ORIGEM
WHERE IDCLIENTE = ID_CLIENTE; -- JUNCAO

/* WHERE = SELECAO*/
SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE, ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE
AND SEXO = 'F';

/* WHERE ID_CLIENTE = ID_CLIENTE
    AND SEXO = 'F'; -> TABELA VERDADE */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE -- PROJECAO
FROM CLIENTE -- ORIGEM
    INNER JOIN ENDERECO -- JUNCAO
    ON IDCLIENTE = ID_CLIENTE 
WHERE SEXO = 'F'; -- SELECAO

/* NOME, SEXO, EMAIL, TIPO, NUMERO */
SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
    INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE;

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO */
SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
    INNER JOIN ENDERECO
    ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
    INNER JOIN TELEFONE
    ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
    
SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE

/* 
    DML - DATA MANIPULATION LANGUAGE
    DDL - DATA DEFINITION LANGUAGE
    DCL - DATA CONTROL LANGUAGE
    TCL - TRANSACTION CONTROL LANGUAGE
 */ 

-- DML
 /* INSERT  */
INSERT INTO CLIENTE VALUES(NULL, 'PAULA', 'M', NULL, '96562654');

INSERT INTO ENDERECO VALUES(NULL, 'JOAQUIM SILVA', 'ALVORADA', 'NITEROI', 'RJ', 9);

/* FILTROS */
SELECT * FROM CLIENTE
WHERE SEXO = 'M';

/* UPDATE */
SELECT * FROM CLIENTE
WHERE IDCLIENTE = 9;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 9;

/* DELETE */
INSERT INTO CLIENTE VALUES(NULL, 'XXX', 'M', NULL, 'XXX');

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 10;

DELETE FROM CLIENTE
WHERE IDCLIENTE = 10;

-- DDL
CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(30) NOT NULL,
    PRECO INT,
    FRETE FLOAT(10,2 ) NOT NULL
);

/* ALTER TABLE */

/* ALTERANDO O NOME DE UMA COLUNA - CHANGE */

ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

DESC PRODUTO;

ALTER TABLE PRODUTO
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;

/* MOLDIFY - ALTERANDO O TIPO */

ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;
