/* SELECAO PROJECAO E JUNCAO */

/* PROJECAO -> É TUDO QUE VOCE QUER VER NA TELA */
SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2  AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW()
FROM CLIENTE;

/* SELECAO -> É U SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA
A CLAUSULA DE SELECAO É O WHERE */
SELECT NOME, SEXO, EMAIL -- PROJECAO
FROM CLIENTE -- ORIGEM
WHERE SEXO = 'F'; -- SELECAO

SELECT NUMERO, TIPO -- PROJECAO
FROM TELEFONE -- ORIGEM
WHERE TIPO = 'CEL'; -- SELECAO

/* JUNCAO -> JOIN*/
SELECT NOME, EMAIL, ID_CLIENTE
FROM CLIENTE;

SELECT IDCLIENTE, BAIRRO, CIDADE
FROM ENDERECO;

/* NOME, SEXO, BAIRRO, CIDADE */
SELECT NOME, SEXO, BAIRRO, CIDADE -- PROJECAO
FROM CLIENTE, ENDERECO -- ORIGEM
WHERE IDCLIENTE = ID_CLIENTE; -- JUNCAO

/* WHERE = SELECAO*/
SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE, ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE
AND SEXO = 'F';

/* WHERE ID_CLIENTE = ID_CLIENTE
    AND SEXO = 'F'; -> TABELA VERDADE */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE -- PROJECAO
FROM CLIENTE -- ORIGEM
    INNER JOIN ENDERECO -- JUNCAO
    ON IDCLIENTE = ID_CLIENTE 
WHERE SEXO = 'F'; -- SELECAO

/* NOME, SEXO, EMAIL, TIPO, NUMERO */
SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
    INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE;

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO */
SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
    INNER JOIN ENDERECO
    ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
    INNER JOIN TELEFONE
    ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
    
SELECT NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO
FROM CLIENTE
    INNER JOIN ENDERECO
    ON IDCLIENTE = ID_CLIENTE
    INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE
