/* DELIMITADOR */
STATUS

DELIMITER $ --ALTERADO DE ; PARA $

SELECT * FROM V_RELATORIO$

/* STORED PROCEDURES */

SELECT 'MAFRA';

DELIMITER $

CREATE PROCEDURE NOME()
BEGIN 
    QUALQUER PROGRAMAÇÃO;
END
$


CREATE PROCEDURE NOME_EMPRESA()
BEGIN
    SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;
END
$

/* CHAMANDO UMA PROCEDURE */

CALL NOME_EMPRESA()$

/* PROCEDURES COM PARAMETROS */

SELECT 10 + 10 AS CONTA;

CREATE PROCEDURE CONTA()
BEGIN
   SELECT 10 + 10 AS CONTA;
END
$

CALL CONTA()$

DROP PROCEDURE CONTA$

CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN
   SELECT NUMERO1 + NUMERO2 AS CONTA;
END
$

CALL CONTA(100, 50)$
CALL CONTA(123142, 346346)$
CALL CONTA(34735, 23423423)$
CALL CONTA(236547, 1231231)$

/* PROCEDURES */

USE PROJETO;

CREATE TABLE CURSOS(
    ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    HORAS INT(3) NOT NULL,
    VALOR FLOAT(10, 2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL, 'JAVA', 30, 500.00);
INSERT INTO CURSOS VALUES(NULL, 'FUNDAMENTOS DE BANCO DE DADOS', 40, 700.00);

DELIMITER #

CREATE PROCEDURE CAD_CURSO (P_NOME VARCHAR(30),
                            P_HORAS INT(3),
                            P_PRECO FLOAT(10,2))
BEGIN
    INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);
END
#

CALL CAD_CURSO(NULL, 'BI SQL SERVER', 35, 3000.00);
CALL CAD_CURSO(NULL, 'POWER BI', 20, 1000.00);
CALL CAD_CURSO(NULL, 'TABLEAU', 30, 1200.00);
CALL CAD_CURSO(NULL, 'EXCEL BASICO', 15, 200.00);
CALL CAD_CURSO(NULL, 'PYTHON AVANCADO', 50, 4000.00);
CALL CAD_CURSO(NULL, 'SPRING BOOT DO ZERO AO MESTRE', 90, 2500.00);
CALL CAD_CURSO(NULL, 'INGLÊS BASICO', 15, 100.00);
CALL CAD_CURSO(NULL, 'MATEMATICA INICIANTE', 10, 150.00);

SELECT * FROM CURSOS;

/* CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS */

DELIMITER #

--PROCEDURE PARA PESQUISAR CURSOS COM A EXATA OU MENOR HORA INFORMADA
CREATE PROCEDURE C_FILTROHORAS (C_HORAS INT(2))
BEGIN
    SELECT NOME, HORAS, VALOR
    FROM CURSOS
    WHERE HORAS <= C_HORAS;
END
#

DELIMITER ;

--PROCEDURE PARA PESQUISAR CURSOS PELO ID

DELIMITER #

CREATE PROCEDURE C_IDCURSO(C_ID INT(2))
BEGIN
    SELECT ID_CURSO, NOME, HORAS, VALOR
    FROM CURSOS
    WHERE ID_CURSO = C_ID;
END
#

DELIMITER ;
--PROCEDURE PARA PESQUISAR CURSOS COM O EXATO OU MENOR VALOR

DELIMITER #

CREATE PROCEDURE C_FILTROVALOR (C_VALOR FLOAT(10,2))
BEGIN
    SELECT NOME, HORAS, VALOR
    FROM CURSOS
    WHERE VALOR <= C_VALOR;
END
#

DELIMITER ;