/* SINTAXE BASICA DE INSERÇÃO - INSERT INTO {TABELA}*/

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES ('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '2293110', 'MATA-LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('JORGE', 'M', NULL, 885755896, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE (NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES ('LILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES ('ANA', 'F', 'ANA@GLOBO.COM', 85548962, '5485569858', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                           ('CARLA', 'F', 'CARLA@TERATI.COM.BR', 7745828, '66574758', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

/* O COMANDO SELECT (PROJEÇÃO) */

SELECT NOW() AS DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO 
    1° - SELECT // Coluna a ser projetada;
    2° - FROM // Tabela a ser filtrada; 
    3° - WHERE // Condição 
*/

SELECT NOME, SEXO 
FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO 
FROM CLIENTE
WHERE SEXO = 'F';
 
SELECT NOME, SEXO 
FROM CLIENTE
WHERE ENDERECO 
LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA */

SELECT NOME, SEXO 
FROM CLIENTE
WHERE ENDERECO 
LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE ENDERECO 
LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE ENDERECO 
LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE ENDERECO 
LIKE '%CENTRO%';